version: "3"

services:
  marax-adapter:
    build: ./containers/marax-adapter
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - marax-storage:/var/log/marax
    restart: always
  telegraf:
    image: telegraf
    depends_on:
      - influxdb
      - marax-adapter
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
      - marax-storage:/var/log/marax
    restart: always
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - ./config/influxdb:/docker-entrypoint-initdb.d
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

volumes:
  grafana-storage:
  influxdb-storage:
  marax-storage:
